# Generated by Django 5.0.6 on 2024-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='test_type',
            field=models.CharField(default='sugar', max_length=20),
        ),
    ]
