# Generated by Django 5.0.6 on 2024-06-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_files_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='test_type',
            field=models.CharField(max_length=20),
        ),
    ]
