# Generated by Django 5.0.6 on 2024-06-21 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_files_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
