# Generated by Django 5.0.6 on 2024-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_is_doctor_user_is_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docterName', models.CharField(max_length=20)),
                ('patientName', models.CharField(max_length=20)),
                ('appointmentDate', models.DateField(auto_now_add=True)),
                ('appointmentTime', models.TimeField(auto_now_add=True)),
                ('reason', models.TextField(max_length=1000)),
            ],
        ),
    ]
